import { CalendarBuilder, CalendarYearBuild } from './calendar-builder';

export const JulianCalendar = CalendarBuilder.from()
  .withName('Earth Calendar')
  .withDescription('The calendar used on Earth')
  .withDay({ name: 'Sunday' })
  .withDay({ name: 'Monday' })
  .withDay({ name: 'Tuesday' })
  .withDay({ name: 'Wednesday' })
  .withDay({ name: 'Thursday' })
  .withDay({ name: 'Friday' })
  .withDay({ name: 'Saturday' })
  .withYear(
    CalendarYearBuild.from()
      .withRepeats(3)
      .withMonth({ name: 'January', length: 31 })
      .withMonth({ name: 'February', length: 28 })
      .withMonth({ name: 'March', length: 31 })
      .withMonth({ name: 'April', length: 30 })
      .withMonth({ name: 'May', length: 31 })
      .withMonth({ name: 'June', length: 30 })
      .withMonth({ name: 'July', length: 31 })
      .withMonth({ name: 'August', length: 31 })
      .withMonth({ name: 'September', length: 30 })
      .withMonth({ name: 'October', length: 31 })
      .withMonth({ name: 'November', length: 30 })
      .withMonth({ name: 'December', length: 31 })
      .build()
  )
  .withYear(
    CalendarYearBuild.from()
      .withRepeats(1)
      .withMonth({ name: 'January', length: 31 })
      .withMonth({ name: 'February', length: 29 })
      .withMonth({ name: 'March', length: 31 })
      .withMonth({ name: 'April', length: 30 })
      .withMonth({ name: 'May', length: 31 })
      .withMonth({ name: 'June', length: 30 })
      .withMonth({ name: 'July', length: 31 })
      .withMonth({ name: 'August', length: 31 })
      .withMonth({ name: 'September', length: 30 })
      .withMonth({ name: 'October', length: 31 })
      .withMonth({ name: 'November', length: 30 })
      .withMonth({ name: 'December', length: 31 })
      .build()
  )
  .build();
